### ISSUE TITLE
taxonomy_term_edit_access() doesn't exist

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/entity_plus#1]
Looks like `taxonomy_term_edit_access()` was removed after Drupal 7. In line https://github.com/backdrop-contrib/entity_plus/blob/b8b3f13cb270b315941ea2c7356044cc76a9ff6c/modules/callbacks.inc#L802

Not clear why it was removed but perhaps can just add directly: ` user_access("edit terms in {$term->vid}")`

**Comment by aaronbowwwls** [comment]
I think taxonomy_term_access() can be used in its place.
```diff --git a/modules/callbacks.inc b/modules/callbacks.inc
index 7826aa7..13792c3 100644
--- a/modules/callbacks.inc
+++ b/modules/callbacks.inc
@@ -799,7 +799,7 @@ function entity_plus_metadata_taxonomy_access($op, $entity = NULL, $account = NU
   if ($entity_plus_type == 'taxonomy_vocabulary') {
     return user_access('administer taxonomy', $account);
   }
-  if (isset($entity) && $op == 'update' && !isset($account) && taxonomy_term_edit_access($entity)) {
+  if (isset($entity) && $op == 'update' && !isset($account) && taxonomy_term_access($entity, $op)) {
     return TRUE;
   }
   if (user_access('administer taxonomy', $account) || user_access('access content', $account) && $op == 'view') {```

**Comment by herbdool** [comment]
@aaronlphillips the only problem is that for some reason `taxonomy_term_access` only checks `$op` for "edit" and "delete". Perhaps we need to just hardcode "edit" into it

**Comment by aaronbowwwls** [comment]
@herbdool good point. I also just noticed that I had my parameters flipped for `taxonomy_term_access`.
I found an issue for the taxonomy module to addresses your point about `$op`, but the fix hasn't made it into core yet.
https://github.com/backdrop/backdrop-issues/issues/3011

Once these changes make it into core, then it might be safe to rely on the taxonomy module to determine access.

**Comment by aaronbowwwls** [comment]
I think this will work:
```diff
diff --git a/modules/callbacks.inc b/modules/callbacks.inc
index 7826aa7..f32ad23 100644
--- a/modules/callbacks.inc
+++ b/modules/callbacks.inc
@@ -799,7 +799,7 @@ function entity_plus_metadata_taxonomy_access($op, $entity = NULL, $account = NU
   if ($entity_plus_type == 'taxonomy_vocabulary') {
     return user_access('administer taxonomy', $account);
   }
-  if (isset($entity) && $op == 'update' && !isset($account) && taxonomy_term_edit_access($entity)) {
+  if (isset($entity) && $op == 'update' && !isset($account) && user_access("edit terms in {$entity->vocabulary}")) {
     return TRUE;
   }
   if (user_access('administer taxonomy', $account) || user_access('access content', $account) && $op == 'view') {```
