### ISSUE TITLE
Change `language` property to `langcode` in node.info.inc

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/entity_plus#110]
The correct name for the node property is `langcode`, not `language`. The schema field should also be changed to `langcode`, since this was changed in Backdrop.  This also needs to be changed in the tests.

**Comment by argiepiano** [comment]
For backward compatibility, perhaps we can wrap the getter and setter of langcode so that it will also take language

**Comment by argiepiano** [comment]
PR #138.

Both properties `language` and `langcode` are available. `language` now works properly (it was pointing to the wrong schema field)

Metadata property `language` is kept for backward compatibility.

**Comment by laryn** [comment]
Looks good. My only question (which I don't have a strong opinion on) is whether to mark some kind of deprecation notice in the code or just plan to keep it indefinitely. And maybe make the first definition the "correct" one, and then duplicate it as the deprecated/backwards compatible but "incorrect" one in the one-liner.

**Comment by argiepiano** [comment]
Thanks, @laryn. I'm having second thoughts about providing `language` as a property. With all other properties, the key of the property info array coincides with the schema column name. In Backdrop, it's widely known that the column `language`  was changed to `langcode`. For contrib modules coming from D7, developers address this change right away. So it seems unnecessary to keep the old property name.

~~Plus, any deprecation notice would have to be placed in multiple spots, most likely in the wrapper methods that can potentially access that property. This becomes messy very quickly.~~

Actually, a deprecation notice could be done by creating custom getter and setter callbacks that invoke `entity_plus_property_verbatim/_get/_set` and additional create a watchdog notice. 

I'm leaning toward nixing `language` altogether, just like everywhere else in Backdrop. Any objections?

**Comment by argiepiano** [comment]
One additional modification needed: the description of the property should say "The code of the language the node is written in"  since the getter will return the code, not the language label (just like in D7).

**Comment by hosef** [comment]
Would it be good to leave language but make it return the translated and human readable name of the language while making langcode consistent with what is in core?

**Comment by argiepiano** [comment]
Getting the human readable name is already possible with wrappers without specifying a new property

`$wrapper->langcode->value()` will return the code
`$wrapper->langcode->label()` will return the human readable label.

This is possible thanks to the magic of property info. As soon as you define an "options list" callback in the property, you tell the wrapper (and therefore other modules like Rules) what the labels are. 

So, I'm not sure we need a separate property for this.

**Comment by hosef** [comment]
Then I think that making it consistent with core would be a good idea.

Perhaps also keeping the old property and adding a deprecation notice for a while to give people a chance to update their custom code would be a good idea too.

**Comment by argiepiano** [comment]
Sounds good! I'll get work on the deprecation notice and changes very soon.

**Comment by argiepiano** [comment]
@hosef I've included deprecation language in the label of the property, rather than creating a new getter that would generate a watchdog message. I feel that this is adequate, as it will primarily show in obvious ways in the Rules data selector, which allows the site builder to know exactly where the deprecation is. Adding a watchdog deprecation notice in the getter can really be very unhelpful and confusing, as the getter can be invoked from many different places, and the watchdog message would not really help someone find where the problem is. 

This is how the property label shows up in the Rules Data Selector:

<img width="680" alt="Screen Shot 2023-01-22 at 9 36 45 PM" src="https://user-images.githubusercontent.com/9938978/213969312-4f594c9f-01db-46b5-8681-250a96935df8.png">

And this is how it shows up in the token tree when Entity Tokens is enabled

<img width="521" alt="Screen Shot 2023-01-22 at 10 07 26 PM" src="https://user-images.githubusercontent.com/9938978/213969412-f127e38c-34a2-49e6-9fb4-041336f8c80a.png">

Incidentally, Entity Tokens automatically returns the label (i.e. "Language neutral" or "English") instead of the column value ("und" or "en") if you use the deprecated `[node:language]`. It's a standard behavior provided by Backdrop's version of Entity Tokens that any token that has an `options list` defined in its property info will return the label rather than the value. This may be considered a bug...   but this is beyond this PR. I'll open an issue in Entity Tokens.  On the other hand the token `[node:langcode]` is handled by core, and returns the language code. 

Metadata wrappers will return the language code using either property, `$w->langcode->value()`  or the deprecated `$w->language->value()`

**Comment by argiepiano** [comment]
Thanks for the [LGTM](https://github.com/backdrop-contrib/entity_plus/pull/138#issuecomment-1400496854) @laryn!  @hosef let me know if this looks good to you too

**Comment by hosef** [comment]
@argiepiano This looks good to me. I have merged it into 1.x
