### ISSUE TITLE
Implement hook_modules_enabled() to create default entities defined by the enabled modules

### ISSUE THREAD

**Issue by VasasA** [backdrop-contrib/entity_plus#119]
Please see the [issue 12 of OG module.](https://github.com/backdrop-contrib/og/issues/12)
The bug of OG fixed by implemented `hook_modules_enabled()` and `_entity_plus_modules_get_default_types()` functions in `entity_plus.module` No need to modify OG's source code. Entity module implements these functions in D7.
Entity module implements further functions in D7, but the Entity Plus doesn't in BD: `hook_modules_disabled()`, `hook_modules_installed()`, `hook_modules_uninstalled()`, `hook_flush_caches()` 
May these also need to be implemented?

```php

/**
 * Implements hook_modules_enabled().
 */
function entity_plus_modules_enabled($modules) {
  foreach (_entity_plus_modules_get_default_types($modules) as $type) {
    _entity_plus_defaults_rebuild($type);
  }
}

/**
 * Gets all entity types for which defaults are provided by the $modules.
 */
function _entity_plus_modules_get_default_types($modules) {
  $types = array();
  foreach (entity_plus_crud_get_info() as $entity_type => $info) {
    if (!empty($info['exportable'])) {
      $hook = isset($info['export']['default hook']) ? $info['export']['default hook'] : 'default_' . $entity_type;
      foreach ($modules as $module) {
        if (module_hook($module, $hook) || module_hook($module, $hook . '_alter')) {
          $types[] = $entity_type;
        }
      }
    }
  }
  return $types;
}
```

**Comment by argiepiano** [comment]
@VasasA thank you for reporting. Have you tested this addition with OG? Does it solve the issue there? If so, can you provide a PR here?

**Comment by VasasA** [comment]
Yes, I tested, and it fixed the [issue 12 of OG module.](https://github.com/backdrop-contrib/og/issues/12)
I provided the PR. :+1:

**Comment by argiepiano** [comment]
Thank you for providing the PR. I'll test.

Can you please also add to your PR the function `entity_modules_disabled()`? (which should  be called `entity_plus_modules_disabled()`)

This is an important function as it removes from the database all module default types when uninstalling a module.

**Comment by VasasA** [comment]
I've implemented the `entity_plus_modules_disabled()` function, but I have got 2 problems:
1. I cannot test this function by OG module, because when I disable the OG, then the `_entity_plus_modules_get_default_types($modules)` function returns an empty array. So the `foreach` loop exits. (See below.) It is the expected behavior, because OG module is disabled, when this function starts. This is how the D7 version Entity works too. D7 version Entity deletes the OG's default types by "Actions" (admin/config/system/actions), and not by `entity_modules_disabled()` function.
2. The `entity_plus_modules_disabled()` function contains 4 constants: ENTITY_IN_CODE, ENTITY_FIXED, ENTITY_OVERRIDDEN, ENTITY_CUSTOM
These constants are defined in the Entity UI module (`entity_ui.module`) So we should insert a dependency into the `entity_plus.info`: `dependencies[] = entity_ui`

**Should I insert the `entity_plus_modules_disabled()` function and the dependency into my PR?**

Implemented `entity_plus_modules_disabled()` function:
```php
/**
 * Implements hook_modules_disabled().
 */
function entity_plus_modules_disabled($modules) {
  foreach (_entity_plus_modules_get_default_types($modules) as $entity_type) {
    $info = entity_get_info($entity_type);

    // Do nothing if the module providing the entity type has been disabled too.
    if (isset($info['module']) && in_array($info['module'], $modules)) {
      return;
    }

    $keys = $info['entity keys'] + array('module' => 'module', 'status' => 'status', 'name' => $info['entity keys']['id']);
    // Remove entities provided in code by one of the disabled modules.
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', $entity_type, '=')
          ->propertyCondition($keys['module'], $modules, 'IN')
          ->propertyCondition($keys['status'], array(ENTITY_IN_CODE, ENTITY_FIXED), 'IN');
    $result = $query->execute();
    if (isset($result[$entity_type])) {
      $entities = entity_load($entity_type, array_keys($result[$entity_type]));
      entity_delete_multiple($entity_type, array_keys($entities));
    }

    // Update overridden entities to be now custom.
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', $entity_type, '=')
          ->propertyCondition($keys['module'], $modules, 'IN')
          ->propertyCondition($keys['status'], ENTITY_OVERRIDDEN, '=');
    $result = $query->execute();
    if (isset($result[$entity_type])) {
      foreach (entity_load($entity_type, array_keys($result[$entity_type])) as $name => $entity) {
        $entity->{$keys['status']} = ENTITY_CUSTOM;
        $entity->{$keys['module']} = NULL;
        entity_save($entity_type, $entity);
      }
    }

    // Rebuild the remaining defaults so any alterations of the disabled modules
    // are gone.
    _entity_plus_defaults_rebuild($entity_type);
  }
}
```

**Comment by argiepiano** [comment]
@VasasA thanks for pasting. 

Regarding the constants, they have been renamed in Entity  Plus to ENTITY_PLUS_XXX, so please change those in the code you pasted there. We don't need to depend in Entity UI.

So, yes, please add entity_plus_modules_disabled to your PR, after changing the names of all the constants.

After you do that I will be able to test and review the code more thoroughly. Thanks for doing this!

**Comment by VasasA** [comment]
:+1:  Thank You for suggestions.
I have changed the names of constants, and updated the PR.

**Comment by argiepiano** [comment]
@VasasA thanks so much for adding those. I've added three comments to your latest PR - changes are needed. Can you please make those changes and update the PR? 

I've tested the code in `entity_plus_modules_enabled()` and it seems to work fine. Once you submit the latest changes I think we will be ready to merge.

**Comment by VasasA** [comment]
Sorry for the deficiencies. I made the changes. I found 2 `entity_load()`, replaced them.

**Comment by VasasA** [comment]
Thank You for the collaboration 😃
