### ISSUE TITLE
Update GHA configuration

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/entity_plus#123]
Seems best to follow @indigoxela's lead on GHA configuration, so we should update to match this latest:

 - https://github.com/backdrop-contrib/i18n/commit/9067c22d665be882c8f06bea88af2f5aa88dee01

**Comment by argiepiano** [comment]
Sounds good to me. Do you want to provide a PR?

**Comment by laryn** [comment]
Yes, I will.

**Comment by argiepiano** [comment]
Thanks, @laryn . For some reason a vocabulary test that passed before is failing now.  I'm going to check what's going on.

**Comment by laryn** [comment]
Strange!

**Comment by indigoxela** [comment]
> For some reason a vocabulary test that passed before is failing now.

One possible reason: tests are now run with the profile cache. To figure out if it's that, remove the `--cache` option from the last line.
If it's caused by the profile cache... hm... not sure.

**Comment by argiepiano** [comment]
Thanks, @indigoxela. I did not have a chance to check yesterday. I'll check what you mentioned today, but I think it has to do with vocabulary comparisons, and the new "original" key.

**Comment by indigoxela** [comment]
> but I think it has to do with vocabulary comparisons, and the new "original" key.

Ah! Nice catch!
