### ISSUE TITLE
Trying to access property 'type' of file entities with a wrapper produces fatal errors

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/entity_plus#136]
~~Apparently the properties of file entities are not defined correctly for metadata wrappers. This may be a legacy of D7, as file entities were not full-fledged entities.~~

Edit: All properties except type are defined in Entity Plus' file `system.info.inc`.   Property `type` needs to be added there (this property was added in D7 by the `file_entity` module

**Comment by argiepiano** [comment]
PR #137 

@laryn, @hosef  - this is a very simple PR that adds metadata for the `type` property for `file` entities. In D7 this metadata was added by the contrib module `file_entity`. 

I'll wait a few days before merging in case you want to test or have feedback. I copied-pasted (and slightly adapted to match the function names in B) from `file_entity`.

**Comment by laryn** [comment]
For posterity, [here's the `file_entity` version](https://git.drupalcode.org/project/file_entity/-/blob/7.x-2.x/file_entity.module#L1024-1040).

LGTM :+1:

**Comment by argiepiano** [comment]
Thank you, @laryn!
