### ISSUE TITLE
Add 'property_type' for core Email field

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/entity_plus#14]
As per https://github.com/backdrop/backdrop-issues/issues/2933, I think the `property_type` key for the Email field should be removed from Backdrop core and added here instead (with the rest of the support for core fields).

**Comment by laryn** [comment]
Sounds good to me if anyone has a chance to make a PR I will test and merge!

**Comment by argiepiano** [comment]
It looks like property_type for field type Email was removed from core but never added to `entity_plus_property.inc`? I'll create a PR soon.

**Comment by argiepiano** [comment]
Created PR #52

**Comment by laryn** [comment]
Thanks again @argiepiano !
