### ISSUE TITLE
Entity Plus is missing entity_plus_entity_property_info_alter()

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/entity_plus#146]
As I was working on fixing some Rules translation test I discovered that, since ported, Entity Plus has been missing an alter hook implementation from D7 that does a few important things - among those, alter the structure of the node property info, and other entities. 

`entity_plus_entity_property_info_alter()` should be placed in the `entity_plus.module`.  (In D7 this was called `entity_entity_property_info_alter()`)

This particular alter hook takes care of invoking a bunch of other sub-hooks in several inc files:
- `entity_plus_metadata_statistics_entity_property_info_alter()`
- `entity_plus_metadata_poll_entity_property_info_alter()`
- `entity_plus_metadata_locale_entity_property_info_alter()`
- `entity_plus_metadata_comment_entity_property_info_alter()`
- `entity_plus_metadata_node_entity_property_info_alter`

None of those sub-hooks are being currently invoked, and therefore the property structures for those entities are not being modified as needed. So far, the only apparent problem caused by this omission is showing in Rules tests.

This is kind of a critical fix.    PR forthcoming.

**Comment by argiepiano** [comment]
PR #147 ready for review. 

This is one of three fixes needed in order for Rules translation to be functional.

**Comment by bugfolder** [comment]
I still find the whole entity/controller structure pretty challenging, but the argument for its need makes sense; this looks pretty straightforward, and the implementation looks good, so, LGTM.

**Comment by argiepiano** [comment]
Thanks, @bugfolder

**Comment by laryn** [comment]
Thanks @argiepiano and @bugfolder!
