### ISSUE TITLE
Add property info  `comment` (node comment settings) to node.info.inc

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/entity_plus#149]
Currently, the property `comment` of nodes is not available to metadata wrappers, and to other modules that use wrappers (for example Views Bulk Operations and Rules). This property indicates whether comments are open, closed or hidden for a specific node.

Adding property info for this column would allow, among other things, to bulk-set this property with VBO (this would solve Backdrop's request https://github.com/backdrop/backdrop-issues/issues/2297), and access/change the values with Rules.

PR coming

**Comment by argiepiano** [comment]
PR #150 ready for review.

**Comment by hosef** [comment]
I looked at the changes and everything looked fine to me. I also ran tests to confirm that this would not break existing functionality.

The changes have been merged into 1.x.

**Comment by laryn** [comment]
Thanks @argiepiano and @hosef!
