### ISSUE TITLE
Prepare wrappers for PHP 8.2

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/entity_plus#159]
Entity metadata wrapper classes all use dynamic properties to get or set values for entity fields. For example, this is very common: `$wrapper->my_field->value();` where `my_field` is a dynamic property of the wrapper, and corresponds to the entity's `my_field` field. 

The solution I'm proposing is to add `#[AllowDynamicProperties]` to the base wrapper class. PR coming.

**Comment by argiepiano** [comment]
PR #159. @laryn, @hosef please take a look when you have a chance.

**Comment by hosef** [comment]
@argiepiano This looks like a straightforward change, and I can't imagine it would break anything.

I think it would be fine to merge this.

**Comment by argiepiano** [comment]
Thanks
