### ISSUE TITLE
Vocabulary test failure after https://github.com/backdrop/backdrop-issues/issues/6197

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/entity_plus#164]
The changes to `TaxonomyVocabulary` made in https://github.com/backdrop/backdrop-issues/issues/6197 are causing a Vocabulary metadata test to fail. 

The issue is that, in that core commit, the property `TaxonomyVocabulary::original` was explicitly declared in the class. This results in all new Vocabulary objects to contain an `original` property with value `null`. The particular tests that fail compare two vocabularies after unsetting `original`. This approach doesn't work anymore. Instead of unsetting, the test should assign a null value to `original` before comparing.

I don't expect the changes in `TaxonomyVocabulary` will cause any other issues with metadata wrappers.

PR coming

**Comment by argiepiano** [comment]
PR submitted and ready for review.

**Comment by argiepiano** [comment]
Test now passes!

**Comment by argiepiano** [comment]
@hosef, @laryn, any chance you can review this so that we can get tests passing again?

**Comment by laryn** [comment]
LGTM, merged!
