### ISSUE TITLE
taxonomy_term's property `vocabulary` must be a required property

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/entity_plus#171]
A year or two ago, when I added a special wrapper for Vocabularies (since they are not entities in Backdrop, like they were in Drupal 7), I missed a single line for the taxonomy_term's `vocabulary` property info: `'required' => TRUE`.

This omission causes Rules not to show the vocabulary selection form element for the action "Create a new Entity". See Rules' [issue 210](https://github.com/backdrop-contrib/rules/issues/210). 

BTW, In D7, the vocabulary property is required, and it also should be in Backdrop. PR coming.

**Comment by argiepiano** [comment]
@bugfolder, @laryn, @hosef, PR provided.

To test:
1. Install Rules and Rules UI
2. Create a rule that reacts to a new node being created (in fact any reaction would work)
3. Add an action "Create a new entity", then select "Taxonomy term" and click "Continue". 
4. At this point, before applying the PR, you won't be prompted to select a vocabulary for the new taxonomy term (which is a bug)
5. Apply the PR and repeat all steps from number 2. This time you should be prompted to provide a vocabulary (as expected).

Thanks!

**Comment by argiepiano** [comment]
PS: the test failure is produced by another bug, see issue #164 

It'd be great if you could review that one too, so that we can do a new release.

**Comment by laryn** [comment]
Merged the other change and tests pass here, too:
![CleanShot 2024-03-28 at 12 56 18@2x](https://github.com/backdrop-contrib/entity_plus/assets/871421/6d9817b0-62a6-40ff-958b-f5c0b204d66f)

LGTM, merged!
