### ISSUE TITLE
Unsupported operand types

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/entity_plus#2]
Trying to make a branch of Rules that uses Entity Plus instead of EMW and I hit this:

> Error: Unsupported operand types in _entity_plus_defaults_rebuild() (line 672 of /path/modules/entity_plus/entity_plus.module).

**Comment by herbdool** [comment]
@laryn do you still get this error even with your latest fixes to your branch of Rules?

**Comment by laryn** [comment]
@herbdool I'll have to test again to be sure. I just submitted the branch as a PR: https://github.com/backdrop-contrib/rules/pull/31

**Comment by laryn** [comment]
I think Rules is all set with a new release that relies on Entity Plus, so closing this.
