### ISSUE TITLE
Entity Plus and Entity UI define the same named constants

### ISSUE THREAD

**Issue by bradbulger** [backdrop-contrib/entity_plus#20]
The entity_plus module uses constants like ENTITY_OVERRIDDEN that are defined by the entity_ui module. Maybe the intention is to move that into core?

**Comment by laryn** [comment]
@bradbulger I haven't investigated too far yet but what's your recommendation here?

1. Add these constants to Entity Plus
2. Add a dependency on Entity UI
3. Move these constants to Backdrop core

**Comment by bradbulger** [comment]
They're originally from the entity module, which is core now, yes? Unless it's something left out on purpose for some reason. I haven't dug into what they mean in practice, that might matter.

**Comment by oadaeh** [comment]
I think for the interim, both Entity Plus and Entity UI should wrap those definitions with something like ```if (!defined(...)) { ... }```. When both are installed, one will win and one will lose, and if the named constants are identical, I do not think it matters which wins or loses.

**Comment by indigoxela** [comment]
Any progress here?

We get **loads** of `Notice: Constant ENTITY_FIXED already defined in include_once() ` in our dblog since the latest update to 1.x-1.0.8.

Offending commit: https://github.com/backdrop-contrib/entity_plus/commit/757d631350de4d9fb97af1d0c00fc99e333f5a62

**Comment by indigoxela** [comment]
Current workaround: if you have both modules installed, comment out the define lines in one of them.

```
entity_plus/entity_plus.module:14:// define('ENTITY_CUSTOM', 0x01);
entity_plus/entity_plus.module:19:// define('ENTITY_IN_DB', 0x01);
entity_plus/entity_plus.module:24:// define('ENTITY_IN_CODE', 0x02);
entity_plus/entity_plus.module:31:// define('ENTITY_OVERRIDDEN', 0x03);
entity_plus/entity_plus.module:37:// define('ENTITY_FIXED', 0x04 | 0x02);

entity_ui/entity_ui.module:10:define('ENTITY_CUSTOM', 0x01);
entity_ui/entity_ui.module:15:define('ENTITY_IN_DB', 0x01);
entity_ui/entity_ui.module:20:define('ENTITY_IN_CODE', 0x02);
entity_ui/entity_ui.module:27:define('ENTITY_OVERRIDDEN', 0x03);
entity_ui/entity_ui.module:33:define('ENTITY_FIXED', 0x04 | 0x02);
```

**Comment by indigoxela** [comment]
Update: just commenting out will likely not be enough for a workaround. I recommend downgrading to entity_plus 1.x-1.0.7.

**Comment by laryn** [comment]
Here's a branch that takes @oadaeh's advice and does a check to see if they are already defined, and I found I also had to check if `entity_ui` was installed since Entity Plus was declaring them first and then Entity UI was throwing the notices:

 - https://github.com/backdrop-contrib/entity_plus/compare/issue-20?expand=1

**Comment by indigoxela** [comment]
As reported in the other issue, branch https://github.com/backdrop-contrib/entity_plus/tree/issue-20 fixes the problem.

**Comment by indigoxela** [comment]
For completeness I did a quick check if Rules is still working with the bugfix branch - it does.

**Comment by laryn** [comment]
Merging based on the review from @indigoxela.
