### ISSUE TITLE
Update to Entity Plus 1.0.4 breaks Ubercart cart display.

### ISSUE THREAD

**Issue by and-e-h** [backdrop-contrib/entity_plus#21]
The following error message is displayed at http://localhost/cart

"Argument 1 passed to backdrop_attributes() must be of the type array, null given, called in /webserver/backdrop/modules/entity_plus/theme/entity_plus.tpl.php on line 33"

Rolling back to Entity Plus 1.0.3 stops the issue and displays the cart properly.

System:
Debian 10.2
PHP 7.3.14-1~deb10u1
Backdrop 1.15
Ubercart 1.0.7-beta
Entity Plus 1.0.4

**Comment by laryn** [comment]
@and-e-h Can you try this and report back if it solves it for you?

https://github.com/backdrop-contrib/entity_plus/commit/39709a0a2bd0afe804e98ad5e22684d869c011c8

**Comment by and-e-h** [comment]
Tested and working! :)

Many thanks laryn.
