### ISSUE TITLE
Replace cache with staticCache 

### ISSUE THREAD

**Issue by docwilmot** [backdrop-contrib/entity_plus#25]
On Simpletests of a module dependent on EP I'm getting dozens of `EXCEPTION: Undefined property: EntityPlusController::$cache`. This because `https://github.com/backdrop/backdrop/pull/2927` was merged in, replacing the `cache` property with `staticCache`.

**Comment by hosef** [comment]
I created a PR to fix this. #26 

In addition to changing the variables to work with the latest version, I also added some code in the constructor to see if the old cache variable was defined by the parent class so that it will be compatible with older versions of Backdrop.

**Comment by laryn** [comment]
Thanks @hosef! Are you interested in co-maintaining this module?

@docwilmot are you able to test the PR on the issue you were having?

**Comment by hosef** [comment]
@laryn Sure, I would be fine with helping to maintain this module.

**Comment by laryn** [comment]
@hosef - [Thanks](https://github.com/backdrop-contrib/entity_plus/commit/db92ecb97c37593bf7381d52de24d3f04ffa77fb)!

**Comment by laryn** [comment]
I'm seeing a lot of these after running database updates on site upgrades which use Entity Plus:

> Notice: Undefined property: RulesEntityController::$cache in EntityPlusController->load() (line 222 of /path/modules/entity_plus/includes/entity_plus.controller.inc).

@hosef I was going to merge the PR but the button is frozen in the position shown in this screenshot. Are you able to?
![Screen Shot 2020-05-20 at 5 36 40 PM](https://user-images.githubusercontent.com/871421/82504248-812f9900-9ac0-11ea-829e-38e2b437b46b.jpg)

**Comment by hosef** [comment]
@laryn It is doing that for me also. I tried to close and reopen the PR, but that did not work.
I can try doing it from the command line if you would like me to do that.

**Comment by laryn** [comment]
@hosef Sounds good, thanks!

**Comment by laryn** [comment]
@hosef Do we need a version check on this to make sure core is `>= 1.16.0`?

**Comment by hosef** [comment]
@laryn I merged the PR and tagged a new release.

**Comment by laryn** [comment]
Thanks!
