### ISSUE TITLE
Still getting entity_plus.controller.inc errors

### ISSUE THREAD

**Issue by and-e-h** [backdrop-contrib/entity_plus#27]
Hi I'm still getting entity_plus issues logged in Backdrop:

Notice: Undefined property: RulesEntityController::$cache in EntityPlusControllerExportable->load() (line 772 of .../backdrop/modules/entity_plus/includes/entity_plus.controller.inc). 

The latest update fixed two error/warning messages I was getting after the Backdrop 1.16.x update, but this one's still around. Thanks for sorting those out! :)

Debian 10.4
PHP 7.3.14-1~deb10u1
MariaDB 5.5.5-10.3.22-MariaDB-0+deb10u1
Backdrop 1.16.1
Entity Plus 1.0.6

**Comment by Egarbeil** [comment]
Also still getting this error: 
Notice: Undefined property: RulesEntityController::$cache in EntityPlusControllerExportable->load() (line 772 of /modules/entity_plus/includes/entity_plus.controller.inc).

WebServer Apache
CentOS
Backdrop 1.16.1
Entity Plus 
PHP 7.0.33
MySQL, MariaDB, or equivalent version 5.5.5-10.0.38-MariaDB

thank you,
Elisabeth

**Comment by and-e-h** [comment]
Hi all, I may have a fix...

Change line 772 from 

> if ($this->cache && !$revision_id) {

to 

> if ($this->staticCache && !$revision_id) {

that seems to work.

**Comment by Egarbeil** [comment]
That works for me as well, but it’s line 772 in the updated version (1.0.6)

Thanks!  Can it be moved into the distribution so we don’t lose the fix?

Elisabeth Garbeil, MBA PMP
Brainwrap LLC
"Being on the web doesn't have to make your head hurt."
www.brainwrap.com
(810) 560-7181
egarbeil@brainwrap.com

**Comment by laryn** [comment]
@and-e-h or @Egarbeil could you submit a PR?

**Comment by Egarbeil** [comment]
@laryn , happy to, but how?  Also, testing, not sure how to do that too - worked on my site but,,,

**Comment by laryn** [comment]
Here's one tutorial on a method of making PRs, by @klonos:
https://backdropcms.org/news/creating-pull-requests-against-core-easy-noob-way

**Comment by laryn** [comment]
Just saw that  a PR was submitted -- thanks @and-e-h!

https://github.com/backdrop-contrib/entity_plus/pull/30

(In the future it's helpful to link it to the issue to help with visibility).
