### ISSUE TITLE
entity_plus_uri function not defined

### ISSUE THREAD

**Issue by earlyburg** [backdrop-contrib/entity_plus#29]
Line 13 of entity_plus/modules/callbacks.inc reads:

    $return = entity_plus_uri($entity_plus_type, $entity);

should read

    $return = entity_uri($entity_plus_type, $entity);

Found this while working on a port of SearchAPI for Backdrop, as it threw a method or function not found as it is not declared anywhere that I noticed. Thank you!

**Comment by docwilmot** [comment]
Note there is already a Search port https://github.com/backdrop-contrib/search_api

**Comment by laryn** [comment]
@earlyburg Thanks -- care to make a quick PR?

**Comment by earlyburg** [comment]
> 
> 
> Note there is already a Search port https://github.com/backdrop-contrib/search_api

@docwilmot Awesome! I will concentrate on porting search_api_solr which I need for a project. Thank you for letting me know.

**Comment by earlyburg** [comment]
> 
> 
> @earlyburg Thanks -- care to make a quick PR?

@laryn  Np. I will do this a bit later, thank you for the entity_plus module

**Comment by laryn** [comment]
@earlyburg I found your PR:
https://github.com/backdrop-contrib/entity_plus/pull/31/files

Thanks! (In the future if you link the PR to the issue it might get seen more quickly, just FYI)
