### ISSUE TITLE
Error when creating or editing content

### ISSUE THREAD

**Issue by sbgraphicdesign** [backdrop-contrib/entity_plus#3]
With this module enabled I'm getting a php error whenever I create or edit content. I've seen this on two separate websites and it appears to be related to the Entity and related modules, such as Entity Plus, Entity Reference etc.
Here's a report from my error log:

> `Error: Call to undefined function geofield_property_info_callback() in entity_plus_metadata_field_entity_property_info() (line 30 of /public_html/modules/entity_plus/modules/field.info.inc).`

I've seen different errors reported by different modules (when I was switching modules on and off to find which one was causing the error) but always they have a callback function error and always appear to be an 'entity' module.

Would love to see a fix as I have a site launching soon with a massive need for this module.

**Comment by laryn** [comment]
I think this looks like an Entity Plus issue so I've transferred it there.

**Comment by sbgraphicdesign** [comment]
Sorry, I should have been clearer. When I switch Focal Point off, I'm able to create and edit content. When I switch Focal Point on, I'm not.

**Comment by laryn** [comment]
You mention it happened with other modules doing this, too -- is it the same error/line number in the entity plus module?

**Comment by sbgraphicdesign** [comment]
No, here's another error message from a second site (which is using Entity reference).

`Error: Call to undefined function entity_metadata_field_default_property_callback() in entityreference_field_property_callback() (line 626 of /public_html/modules/entityreference/entityreference.module).`

At this point I realised that Focal Point was the last module I'd installed, so I uninstalled it and everything starting working again.

The errors looked very similar (field_property_callback) which is why I feel it's related to the Entity module, and/or related modules.

**Comment by laryn** [comment]
Can you provide a list of modules you're using on each site?

**Comment by sbgraphicdesign** [comment]
**Non Core Modules on Site 1:**
addressfield
better_exposed_filters
captcha
default_views_config
devel
entity_metadata_wrapper
entity_plus
entity_ui
entityreference
feeds
feeds_facebook
field_group
field_sql_norevisions
focal_point
gdpr_cookies
geocoder
geofield
geophp
google_fonts
googleanalytics
html5_upload
image_effects
image_url_formatter
job_scheduler
libraries
rabbit_hole
recaptcha
seo_meta
shariff
simple_gmap
special_menu_items
srcset_image
views_data_export
vimeo_link_formatter-1.x-1.0.0
webform
xmlsitemap
youtube-1.x-1.0.1

**Non Core Modules on Site 2:**
adaptive_image
addressfield
bg_image_formatter
entity_metadata_wrapper
entity_plus
entity_ui
entityreference
feeds
feeds_facebook
focal_point
gdpr_cookies
geocoder
geofield
geophp
googleanalytics
honeypot
image_url_formatter
job_scheduler
libraries
responsive_favicons
rrssb
rules
semanticviews
shariff
simple_gmap
token_filter
xmlsitemap

Many thanks for all this btw!

**Comment by laryn** [comment]
There's a conflict between Entity Plus and Entity Metadata Wrapper which may be to blame here (just speculating since I know about the conflict and both modules are installed on both sites). Which modules in use here require EMW? (EMW is the one that is being phased out in favor of E+).

It's a different error, but see: https://github.com/backdrop-contrib/entityreference/issues/17

**Comment by sbgraphicdesign** [comment]
Yeah I realised I had Entity Metadata Wrapper & Entity UI still installed from when I tried to install Rules. Have uninstalled both modules (and checked database for any reference just in case) and I'm still getting the same error with Focal Point.

Sorry!

**Comment by sbgraphicdesign** [comment]
Not sure if this is related but just got this error when doing a database update for another module update:

`Warning: class_implements(): Class BackdropDefaultEntityController does not exist and could not be loaded in entity_plus_entity_info_alter() (line 199 of /public_html/modules/entity_plus/entity_plus.module).`

**Comment by laryn** [comment]
Just to check -- do you have the latest version of Entity Plus installed?

**Comment by sbgraphicdesign** [comment]
Yes, 1.0.2 is the version I have installed.

**Comment by laryn** [comment]
The error at the top references `geofield` -- can you have `focal point` enabled if you turn off `geofield`?

**Comment by sbgraphicdesign** [comment]
Sorry, no I'm now getting

`Error: Call to undefined function entity_metadata_field_default_property_callback() in entityreference_field_property_callback() (line 626 of /public_html/modules/entityreference/entityreference.module).`

Additionally (and this was before I enabled Focal Point) I'm getting the following warnings:

`Warning: class_implements(): Class BackdropDefaultEntityController does not exist and could not be loaded in entity_plus_crud_get_info() (line 127 of /public_html/modules/entity_plus/entity_plus.module).
Warning: in_array() expects parameter 2 to be array, boolean given in entity_plus_crud_get_info() (line 127 of /public_html/modules/entity_plus/entity_plus.module).`

**Comment by laryn** [comment]
Looks like @herbdool is on the case for that first error over in Entity Reference: 
https://github.com/backdrop-contrib/entityreference/issues/18

The second may be an Entity Plus issue so this issue can serve as the space for conversation on that one. Do you want to tweak the title and maybe update the first post to clarify the current status of this issue?

**Comment by sbgraphicdesign** [comment]
@laryn I'm really sorry for messing you around. I've now set up a new backdrop install to chase this issue down, and it's definitely Geofield that is causing the error. I'll start a new issue.

**Comment by laryn** [comment]
@sbgraphicdesign I'll make sure not to transfer your new issue out of geofield -- sorry about that!
