### ISSUE TITLE
undefined function X_property_info_callback()

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/entity_plus#37]
I was enabling some geo-related modules and the site WSOD on me, with this in the logs:

`Error: Call to undefined function geofield_property_info_callback() in entity_plus_metadata_field_entity_property_info() (line 30 of /app/modules/entity_plus/modules/field.info.inc).`

This brought me also to [D7 Entity Issue 1312374](https://www.drupal.org/project/entity/issues/1312374) and [a patch by Alan D.](https://www.drupal.org/project/entity/issues/1312374#comment-11865730) that prevents the fatal error and sends the error to the watchdog, which seems friendlier.

**Comment by laryn** [comment]
@hosef Does this look okay to you?
https://github.com/backdrop-contrib/entity_plus/pull/38

**Comment by hosef** [comment]
@laryn I took a look at the PR, and that looks like a reasonable fix for the issue. :+1:

**Comment by laryn** [comment]
Thanks @hosef closing with https://github.com/backdrop-contrib/entity_plus/commit/99ccc95e3847024d80d641d098dc66494e3717ce
