### ISSUE TITLE
Latest stable release breaks Metatag functionality

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/entity_plus#39]
One of the side effects of release 1.x-1.0.8 is that it prevents Metatag from working.

I had to downgrade to entity_plus to 1.x-1.0.7 to get that working again. Could some of the maintainers please have a look?

@laryn or @hosef ?

**Comment by laryn** [comment]
@indigoxela Can you please expand on how it prevents Metatag from working? I have a site running both (although I realize while investigating this that it's running Metatag 1.x-1.21.5).

**Comment by indigoxela** [comment]
@laryn sure, sorry for the sparse report:

1. Install Metatag latest stable
2. Override front page meta title (admin/config/metadata/metatags/config/global%3Afrontpage)
3. Flush caches
4. Visit front page and check that the meta title works
5. Install entity_plus AND entity_ui latest stable
6. Visit front page - custom title gone
7. Visit admin/config/metadata/metatags/config/global%3Afrontpage
8. See the empty page (no form items)
9. Disable module entity_plus
10. Visit front page - custom page meta title is back

Note: this time I was able to "fix" it in a testing web by commenting out all "define" in entity_plus while module was disabled. Re-enabling it didn't break metatag again.

**Comment by indigoxela** [comment]
Another note: on the site I first saw the problems, rules is installed (requires both modules), so I couldn't easily disable the entity_plus module.

**Comment by oadaeh** [comment]
Is this a duplicate of https://github.com/backdrop-contrib/entity_plus/issues/20 ?

**Comment by laryn** [comment]
@oadaeh I think it may be.

@indigoxela Can you verify that [the branch here](https://github.com/backdrop-contrib/entity_plus/compare/issue-20?expand=1) or commenting out the constants and then clearing the caches solves the problem above? I installed Metatag on a dev site that is running the Entity Plus branch above, along with Entity UI, and the front page meta title is working.

**Comment by indigoxela** [comment]
Yep, it's a duplicate. This is what I tried:

1. Uninstall entity_plus
2. Get the branch, replace module code, enable
3. Visit front page and metatag admin form - both OK
4. Flush caches several times and repeated previous step - still OK

Works! :+1:
