### ISSUE TITLE
Undefined property: UcCartItemController::$cache

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/entity_plus#42]
Getting this type error for a number of different controllers while testing Ubercart:

> Notice: Undefined property: UcCartItemController::$cache in EntityPlusController->load() (line 222 of /app/modules/entity_plus/includes/entity_plus.controller.inc).

I believe that it might need to be changed in entity_plus to `$this->entityCache` which is defined in `DefaultEntityController`.

**Comment by herbdool** [comment]
Oops just realized that my local copy was not up to date. Looks like there was already a fix to change it to `$this->staticCache` (instead of `$this->entityCache`. Which one is right? Not sure.

**Comment by laryn** [comment]
Question for @hosef ☝️

**Comment by laryn** [comment]
Oh, looks like he's the one that provided the PR:
https://github.com/backdrop-contrib/entity_plus/issues/25

**Comment by herbdool** [comment]
I think this is good enough.
