### ISSUE TITLE
Undefined function: entity_property_extract_innermost_type() in views handler

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/entity_plus#43]
This https://github.com/backdrop-contrib/entity_plus/blob/b4578f6b22c151f83946da822b262fe3d0c87704/views/handlers/entity_plus_views_handler_field_entity.inc#L45

Should be changed to `$this->field_entity_type = entity_plus_property_extract_innermost_type($this->definition['type']);`

**Comment by laryn** [comment]
Thanks @herbdool !
