### ISSUE TITLE
Call to undefined function entity_view() ...line 78... /entity_plus/views/plugins/entity_plus_views_plugin_row_entity_view.inc

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/entity_plus#46]
I am using Entity Plus 1.x-1.0.10 with Search API & Search API Views 1.x-1.0.03. When I configure a new Search Index and create a View of that index type, I receive the fatal error referenced in the title. It is a node search, not custom entities or any other custom code at this point.

Changing that line (78) in /entity_plus/views/plugins/entity_plus_views_plugin_row_entity_view.inc to entity_plus_view() and line 94 from entity_id() to entity_plus_id() seems to resolve the issue.

**Comment by laryn** [comment]
Thank you @erictoupin (and @blimking on the Backdrop forum who noted the same issue) -- I found a few other instances where `entity_view` should be `entity_plus_view` and changed them all at once. Please test the latest release (1.x-1.0.11) and let me know if you find any further issues!

**Comment by laryn** [comment]
Looks like I missed the comment about line 94 and `entity_id()`. I found another instance of that as well.
