### ISSUE TITLE
theme_entity_plus_property is not defined

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/entity_plus#49]
The function `theme_entity_plus_property` doesn't seem to be defined anywhere, despite the direction to `@see theme_entity_plus_property()` in line 13 of `entity_plus.theme.inc`. 

This is function should be the equivalent of Drupal 7's `theme_entity_property`, which is defined in the file `entity.theme.inc`. Is there a reason why it's not included in Backdrop's version of Entity API?

**Comment by laryn** [comment]
Oversight perhaps as pieces were pulled out (some of Entity API went in core and this module tried to gather what remained) -- care to make a PR?

**Comment by argiepiano** [comment]
OK, will do soon. 

In fact, the function `template_process_entity_plus_property()` in `entity_plus.theme.inc` needs to be completely removed, as the whole theme process layer was [removed from Backdrop](https://docs.backdropcms.org/change-records/removed-theme-process-layer).

I'm thinking there are two possible paths: 

(1) we could incorporate the function `theme_entity_plus_property` and its preprocess function `template_preprocess_entity_plus_property` (transcribed from Drupal 7's Entity API) to automatically render the entity's properties when viewed (to render these properties, one must include `'extra fields controller class' => 'EntityDefaultExtraFieldsController'` in hook_entity_info), OR 

(2) not include these theme functions at all, which would mean that developers would need to manually create render arrays to display their custom entity's properties within `function buildContent` in their implementation of `EntityPlusController`  

I'm leaning toward (1) for the ease of use.

**Comment by argiepiano** [comment]
Pull request done in  #50

**Comment by laryn** [comment]
Thank you @argiepiano
