### ISSUE TITLE
cannot update due to missing version

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/entity_plus#53]
Trying to update entity plus to the latest version, I got a message from paragraph that in needs entity plus version > 1.0.5, even I'm installing entity plus 1.0.12. The list of modules doesn't show entity plus version, as if it couldn't find it.

**Comment by robertgarrigos** [comment]
![Modules___ICEC_-_International_Commission_of_European_Citizens](https://user-images.githubusercontent.com/105581/121179555-2ea65380-c860-11eb-9159-616fbf8a3c51.jpg)

**Comment by laryn** [comment]
@robertgarrigos Did you at one point download a dev version from Github directly (not through the releases or project installer)?

**Comment by robertgarrigos** [comment]
Not aware of. I downloaded from GitHub the latest release, not dev. I update all my backdrop sites in the same way. It's easier. Just download any needed module and upload to server with rsync. I just realize that other modules updated this way have the same problem of missing version...

**Comment by robertgarrigos** [comment]
I see that version numbers are missing in the database if not installed with the project manager. Isn't that weird???

**Comment by laryn** [comment]
The version number should be there if you get the packaged version:

![Screen Shot 2021-06-08 at 11 13 36 AM](https://user-images.githubusercontent.com/871421/121220972-baad8080-c84a-11eb-908e-dd0a182c831b.jpg)

The two underneath probably don't include the version number though.

**Comment by robertgarrigos** [comment]
arghhhh... didn't know that... thanks.
