### ISSUE TITLE
entity_plus_type_is_fieldable() is not defined

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/entity_plus#54]
The method `invoke` of class `EntityPlusController` in file `entity_plus.controller.inc` (line 378) calls the function `entity_plus_type_is_fieldable()`. This function is undefined. This seems to be an oversight when the module was ported from Drupal 7. The Drupal 7 version of entity_plus includes the corresponding function called `entity_type_is_fieldable`, which is defined in file `entity.module`.

As a result the field module is never notified when a bundle entity (i.e. entities that define bundles, as in `entity_type` entities) is inserted, deleted or updated. 

Proposed solution: port the Drupal 7 `entity_type_is_fieldable` function as `entity_plus_type_is_fieldable`.

**Comment by laryn** [comment]
Sounds good. Are you able to provide a PR?

**Comment by argiepiano** [comment]
@laryn , I've created a PR to add this missing function. 

However, I think this addition may actually not matter. In my experience, "entityType'" entities (that is, configuration entities that define bundles, and therefore contain the key 'bundle of' in their `hook_entity_info` definitions) use `EntityPlusControllerExportable` as their controller class, rather than `EntityPlusController`. Therefore the code that invokes `entity_plus_type_is_fieldable` in `EntityPlusController` may never be reached. 

Anyway, it's there in case I'm wrong :)

**Comment by laryn** [comment]
I merged it -- if the function call is there in the code I'd like to have the function exist. If we ever chop out all calls to that function we can consider chopping that little function out too.
