### ISSUE TITLE
Function entity_load_single() is undefined 

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/entity_plus#55]
The method `render_entity_link` in class  `entity_plus_views_handler_field_entity` defined in file `entity_plus_views_handler_field_entity.inc` invokes the undefined function  `entity_load_single()` in line 162 and 183.

As explained in the Backdrop documentation for the function `entity_load`, the old Drupal's Entity API function `entity_load_single` has been replaced in Backdrop by `entity_load`, and the old Drupal function `entity_load` has been replace in Backdrop by `entity_load_multiple`. This means that the old `entity_load_single` no longer exists in Backdrop.

Proposed solution: rewrite lines 162 and 183 above to invoke `entity_load` instead.

**Comment by jayelless** [comment]
The same problem exists in class entity_plus_views_handler_area_entity.

**Comment by argiepiano** [comment]
PR #56 has been created. Hoping this will be merged soon...

**Comment by laryn** [comment]
Thanks @argiepiano and @jayelless -- much appreciated.
