### ISSUE TITLE
Error: Call to undefined function views_ui_build_form_url() in entity_plus_views_handler_area_entity.inc

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/entity_plus#57]
This error is thrown when trying to add a Rendered Entity to the header or footer of a View:

`Error: Call to undefined function views_ui_build_form_url() in entity_plus_views_handler_area_entity->options_form() (line 34 of...`

`views_ui_build_form_url()` existed in Drupal 7, but it was renamed to `views_ui_build_form_path()` in Backdrop. 

**How to reproduce the error:**
0. Be sure entity_plus is enabled
1. Create a View
2. Click "Add" in the "Header" fieldset in the View creation page
3. Check "Entity: Rendered entity"
4. Click "Add and configure header"

The Ajax call is aborted. Check the "Recent log messages" to see the error pasted above.

**Proposed solution:**
Rename the  call to` views_ui_build_form_url()` to `views_ui_build_form_path()` in line 34 of `entity_plus_views_handler_area_entity.inc`

**Comment by argiepiano** [comment]
Created PR #58

**Comment by laryn** [comment]
Good catch @argiepiano -- here's the commit that made the core change (although we may have missed creating a change record or deprecated function for this, which could be a separate issue in core):

 - https://github.com/backdrop/backdrop/commit/b65674193ba54ff1cc7714793f2673b9fed1b47f
