### ISSUE TITLE
Adjust due to `file_entity` being in core

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/entity_plus#65]
There are a few places where `entity_plus_access` is referenced but this function doesn't exist and should simply be `entity_access`. These were likely porting search-and-replace errors.

**Comment by laryn** [comment]
Well it's early on a Saturday...

https://github.com/backdrop-contrib/entity_plus/blob/1.x/entity_plus.module#L378-L410

Changing the scope to more pointedly address the bit of code that prompted this.

**Comment by laryn** [comment]
```
  // File entity has it's own entity_plus_access function.
  if (!module_exists('file_entity')) {
    $entity_plus_info['file']['access callback'] = 'entity_plus_metadata_file_access';
  }
```
https://github.com/backdrop-contrib/entity_plus/blob/1.x/entity_plus.module#L270-L273

**Comment by argiepiano** [comment]
@laryn , I'm not sure what this issue means. I don't see a PR and this doesn't seem to be a bug. Can we close this?

**Comment by laryn** [comment]
@argiepiano Sorry I just reread my comments and do see that was quite a mess.

The issue that remains here is that file entity went into core (https://github.com/backdrop/backdrop-issues/issues/2632) but it went directly in the file module, not in a separate ‘file _entity’ module. Maybe the line checking if the file entity module exists can just be chopped out?

**Comment by argiepiano** [comment]
Thanks, @laryn. I've been looking into this further. Not only did Backdrop add file entities into core, but it also added `file_access()`, which makes the code for the 'access callback' provided in Entity Plus more similar to the 'access callback' functions for other entities like nodes, etc.  The current code in Entity Plus worked around the fact that `file_access` did not exist. Additionally, file_access also has the ability to check for ops other than just 'view' - it can also check for   "download", "update", "delete" and  "create".

I will provide a PR to make the change you suggest about (getting rid of checking if the file_entity module exists), and will modify `entity_plus_metadata_file_access()` to make use of Backdrop's `file_access` the same way `entity_plus_metadata_no_hook_node_access` makes use of `node_access`.

**Comment by argiepiano** [comment]
PR #105 . @laryn , I've done testing with metadata wrappers by loading a file and a user and doing access checks as follows:
```php
dpm($file_wrapper->entityAccess('download', $user));
```
I tested all 5 ops, create, download, delete, update and view. Everything seems to be working properly. Please review.

(Another way to test, of course, is by calling `entity_plus_access()`)

**Comment by laryn** [comment]
@argiepiano Great! I just had a simple question in the PR related to wrapping text in the `EntityMalformedException` call in `t()`. I checked in core and it looks inconsistent, interestingly:

 - https://github.com/backdrop/backdrop/search?q=EntityMalformedException

**Comment by argiepiano** [comment]
I'll add that. I'll open a separate issue to add it to other instances of `EntityMalformedException` in Entity Plus

**Comment by argiepiano** [comment]
I've added `t()` around the argument to `EntityMalformedException`. If the code looks good to you, let me know and we can merge this.

**Comment by laryn** [comment]
@argiepiano I think it looks good! Thanks again.
