### ISSUE TITLE
User roles aren't integers

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/entity_plus#68]
I'm debugging some tests in the Rules module and came across an error where it was trying to enforce the role as an integer. This must be a carry-over from role IDs in Drupal 7 but since we don't have numeric role IDs anymore this should not be enforced as an integer.

**Comment by argiepiano** [comment]
I found the same issue myself and was able to fix it. The problem was in function `entity_plus_metadata_user_get_properties`, which should return the machine names of the roles rather than integers. See #84 and the PR #85
