### ISSUE TITLE
Best place to document additional hook_entity_info keys and functions introduced by entity_plus

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/entity_plus#70]
The Drupal 7 contrib module `entity`, which is the module on which `entity_plus` is based, introduced all `hook_entity_info` keys in the file `entity.api.php`. While many of these keys now have made it into core in Backdrop, there are a few that remained only in `entity_plus` that are not documented anywhere. 

What might be the best place to document? Options: 1) creating a `entity_plus.api.php`, 2) in the readme file, 3) in the module wiki. Any thoughts?  Without this information, it's hard for people to understand the benefits of this module beyond the use of `entity_metadata_wrapper()`.

These are the `hook_entity_info` keys that, as far as I can tell, are used in `entity_plus` and not in core:

- extra fields controller class
- module
- entity keys 
--name
-- status
-- module
- view callback
- deletion callback
- save callback
- creation callback
- form callback (though this is not used anywhere in Drupal's contrib Entity API)
- plural label

As a side note: it would also be great to create an example module to show the potential of `entity_plus` and `entity_ui`, something similar to Drupal 7 [Typical Entity Example](https://www.drupal.org/project/typical_entity_example). Does this exist already in Backdrop?

**Comment by laryn** [comment]
@argiepiano I think having an `entity_plus.api.php` would be great -- possibly with more detailed info in the Wiki if appropriate. I am not aware of an example module similar to what you describe but I agree it would be helpful! Are you able to take these on?

**Comment by argiepiano** [comment]
@laryn yes, I can create that file in the next few days. 

In the meantime this weekend I put together an example module [Basic Entity Plus Example](https://github.com/backdrop-contrib/basic_entity_plus_example) that shows how to create a custom entity with Entity Plus and Entity UI. I tried documenting most of it.

**Comment by laryn** [comment]
Noting here that I've linked the example module in the README and also cut a lengthy section from the README and moved it into the Wiki.
