### ISSUE TITLE
Taxonomy info still mentions `vid`

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/entity_plus#71]
https://github.com/backdrop-contrib/entity_plus/blob/1.x/modules/taxonomy.info.inc

The vocabulary info is still referencing a (non-existent in Backdrop) `vid` for vocabularies.

**Comment by laryn** [comment]
https://github.com/backdrop-contrib/entity_plus/search?q=vid

**Comment by argiepiano** [comment]
A couple of these vid mentions actually refer to "version ID", which unfortunately is the column used to store the revision id for some entities like nodes. However other mentions do refer to vocabulary ids, and should be cleaned. I'll get to that soon
