### ISSUE TITLE
With Backdrop >= 7.15 we can use entity_plus_language() ???

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/entity_plus#72]
In https://github.com/backdrop-contrib/entity_plus/blob/b8c7dc479e43152fd708f9208fe5e75dc855d055/modules/callbacks.inc#L554

```
// With Backdrop >= 7.15 we can use entity_plus_language().
  if (function_exists('entity_plus_language')) {
    $default_langcode = entity_plus_language($entity_plus_type, $entity);
  }
```

There doesn't seem to be an `entity_plus_language()` function so this comment is cryptic. Since it doesn't seem to be in this module nor in core, I'm looking for an alternative.

**Comment by laryn** [comment]
Here's the D7 issue:

 - https://www.drupal.org/project/entity/issues/1376126

_(Looks like a search and replace error in that comment regarding Backdrop >= 7.15)_

**Comment by laryn** [comment]
https://github.com/backdrop/backdrop/pull/1955#discussion_r136875107

**Comment by laryn** [comment]
@herbdool 
Care to add a PR to put `entity_plus_language` into this module?

**Comment by herbdool** [comment]
In the meanwhile, I think this is equivalent for most use cases: `$langcode = !empty($entity->langcode) ? $entity->langcode : LANGUAGE_NONE;` so not a big deal. But would be good to fix that section - it looks like it was a search/replace from Drupal > Backdrop.

**Comment by herbdool** [comment]
@laryn we were thinking the same thing.

**Comment by argiepiano** [comment]
I've created a PR that adds `entity_plus_language()`, removed the search/replace "7.15" comment and documented two new keys for `hook_entity_info` in `entity_plus.api.php`. The new keys are `language` and 'language callback'. I've done some testing and it works fine. Please take a look and let me know if you are OK merging.

**Comment by argiepiano** [comment]
PR merged
