### ISSUE TITLE
Missing entity_revision_is_default function

### ISSUE THREAD

**Issue by oadaeh** [backdrop-contrib/entity_plus#79]
The D7 Entity API module provided a function called entity_revision_is_default that is not either in Backdrop core, Entity UI, or this module: https://git.drupalcode.org/project/entity/-/blob/7.x-1.x/entity.module#L434

The Field Collection module uses that function in a couple of places. I can just add it to that module for its own use, or I can create a PR to add it to this module. Which would you prefer?

**Comment by argiepiano** [comment]
@oadaeh , thanks for reporting. Like all functions of Entity Plus when it was ported from Drupal 7 Entity API (a contrib module), the namespace was changed to `entity_plus`. 

The correct function name in Entity Plus is `entity_plus_revision_is_default()`. You'll need to invoke that function, which is pretty identical to the original D7 one. No PR needed. 

Please let me know  if I'm not understanding your question.

**Comment by oadaeh** [comment]
Ah, I didn't even think to look for that name, though I did see it elsewhere, which is why I thought it wasn't included: https://github.com/backdrop-contrib/entity_plus/blob/4acf2f69ee87704fc836df04d73ba811d15160a5/entity_plus.module#L656
Thanks for the feedback.
