### ISSUE TITLE
The `roles` user property should be of type `list<token>`, not `list<text>` 

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/entity_plus#92]
The `roles` property info provided in `user.info.inc` should define roles as  type `list<token>`. Entity Plus uses the type `token` to mean "machine name". Using this type will assure that the property setter fails if it receives something other than a machine name. Currently the setter accepts any text, including hyphens and uppercase when setting roles. 

PR coming

**Comment by laryn** [comment]
Good catch.
