### ISSUE TITLE
Clean up coding to adhere to coding standards

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/entity_plus#98]
Tests for coding standards consistently fail

**Comment by argiepiano** [comment]
@laryn , I was going to start cleaning up to adhere to coding standards, but I noticed that Backdrop core actually doesn't have these coding standard tests as far as I can tell. I'm wondering if we are being just overly meticulous by running these tests? Some of them, like the requirement that classes use UpperCamel labeling without underscores are impossible to change without changing core classes... for example all Views classes use underscores and lowercase naming. Any thoughts?

**Comment by laryn** [comment]
@argiepiano We may need to add certain files to the ignore list. 

e.g. 
https://github.com/backdrop-contrib/paragraphs/blob/1.x-1.x/.github/workflows/coding-standards.yml#L36
